// Central icon/image registry. Paths point to files in the icons/ folder.
// To swap art, just replace the PNG file with the same name.
const ICONS = {
  zones_map: "icons/zones_map.png",
  alliance: "icons/alliance.png",
  damage_ui: "icons/damage_ui.png",
  defense_ui: "icons/defense_ui.png",
  upgrade: "icons/upgrade.png",
  settings_ui: "icons/settings_ui.png",
  ellipsis: "icons/ellipsis.png",
  globe: "icons/globe.png",
  resource_bread: "icons/resource_bread.png",
  resource_brick: "icons/resource_brick.png",
  resource_bronze: "icons/resource_bronze.png",
  resource_cloth: "icons/resource_cloth.png",
  resource_concrete: "icons/resource_concrete.png",
  resource_energy_potion: "icons/resource_energy_potion.png",
  resource_furniture: "icons/resource_furniture.png",
  resource_glass: "icons/resource_glass.png",
  resource_health_potion: "icons/resource_health_potion.png",
  resource_honey_bread: "icons/resource_honey_bread.png",
  resource_jewelry: "icons/resource_jewelry.png",
  resource_large_energy_potion: "icons/resource_large_energy_potion.png",
  resource_legendary_energy_potion: "icons/resource_legendary_energy_potion.png",
  resource_medium_energy_potion: "icons/resource_medium_energy_potion.png",
  resource_plank: "icons/resource_plank.png",
  resource_small_energy_potion: "icons/resource_small_energy_potion.png",
  resource_steel: "icons/resource_steel.png",
  resource_toasted_bread: "icons/resource_toasted_bread.png",
  resource_lead: "icons/resource_lead.png",
  resource_meat: "icons/resource_meat.png",
  resource_salt: "icons/resource_salt.png",
  resource_wood: "icons/resource_wood.png",
  resource_stone: "icons/resource_stone.png",
  resource_food: "icons/resource_food.png",
  resource_coal: "icons/resource_coal.png",
  resource_iron: "icons/resource_iron.png",
  resource_gold: "icons/resource_gold.png",
  resource_cotton: "icons/resource_cotton.png",
  resource_leather: "icons/resource_leather.png",
  resource_sand: "icons/resource_sand.png",
  resource_gemstones: "icons/resource_gemstones.png",
  resource_water: "icons/resource_water.png",
  resource_copper: "icons/resource_copper.png",
  resource_silver: "icons/resource_silver.png",
  resource_zinc: "icons/resource_zinc.png",
  resource_magic_stones: "icons/resource_magic_stones.png",
  resource_herbs: "icons/resource_herbs.png",
  resource_honey: "icons/resource_honey.png",
  resource_armor_cloth: "icons/resource_armor_cloth.png",
  resource_armor_leather: "icons/resource_armor_leather.png",
  resource_armor_iron: "icons/resource_armor_iron.png",
  resource_armor_steel: "icons/resource_armor_steel.png",
  resource_armor_plate: "icons/resource_armor_plate.png",
  resource_helmet_leather: "icons/resource_helmet_leather.png",
  resource_helmet_iron: "icons/resource_helmet_iron.png",
  resource_helmet_steel: "icons/resource_helmet_steel.png",
  resource_helmet_crown: "icons/resource_helmet_crown.png",
  resource_boots_leather: "icons/resource_boots_leather.png",
  resource_boots_iron: "icons/resource_boots_iron.png",
  resource_boots_wind: "icons/resource_boots_wind.png",
  gem: "icons/gem.png",
  energy: "icons/energy.png",
  trophy: "icons/trophy.png",
  gold_coin: "icons/gold_coin.png",
  shard: "icons/shard.png",
  book_codex: "icons/book_codex.png",
  heart_hp: "icons/heart_hp.png",
  mana: "icons/mana.png",
  lock: "icons/lock.png",
  bag_full: "icons/bag_full.png",
  market_chart: "icons/market_chart.png",
  craft: "icons/craft.png",
  business: "icons/business.png",

  // New icons — waiting to know where each one is used
  bell: "icons/bell.png",
  leaderboard_trophy: "icons/leaderboard_trophy.png",
  spellbook: "icons/spellbook.png",
  class_shield: "icons/class_shield.png",
  levelup_badge: "icons/levelup_badge.png",
  quest_scroll: "icons/quest_scroll.png",
  global_chat: "icons/global_chat.png",
  star_coin: "icons/star_coin.png",
  upgrade_scroll: "icons/upgrade_scroll.png",

  // Class icons — one per playable class (replaces the emoji avatar)
  class_warrior: "icons/class_warrior.png",
  class_archer: "icons/class_archer.png",
  class_mage: "icons/class_mage.png",
  class_support: "icons/class_support.png",
  class_merchant: "icons/class_merchant.png",

  // Kingdom icons — one per one of the six kingdoms (Alliance tab)
  kingdom_europe: "icons/kingdom_europe.png",
  kingdom_asia: "icons/kingdom_asia.png",
  kingdom_arab_world: "icons/kingdom_arab_world.png",
  kingdom_africa: "icons/kingdom_africa.png",
  kingdom_north_america: "icons/kingdom_north_america.png",
  kingdom_south_america: "icons/kingdom_south_america.png"
};
